services:

  rabbitmq:

    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest


  consumer:

    build: .
    container_name: etl_consumer

    command: ["python", "consumer/consumer.py", "all"]
    restart: always # Se reinicia automáticamente si falla
    env_file:
      - ./config/.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq

  # Tarea de corta duración (one-shot): El orquestador de ingesta
  ingestion_task:
    build: .
    container_name: etl_ingestion_task
    env_file:
      - ./config/.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
    driver: local